from sqlalchemy import Column, Integer, String, Float, DateTime
from sqlalchemy.sql import func
from app.core.database import Base


class PaidDetail(Base):
    __tablename__ = "paid_detail"

    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(String, nullable=False, index=True)
    date_range = Column(String, nullable=False)

    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    cost = Column(Float, default=0)
    ctr = Column(Float, default=0)
    cpc = Column(Float, default=0)
    cpm = Column(Float, default=0)
    total_gmv = Column(Float, default=0)
    total_orders = Column(Integer, default=0)
    direct_gmv = Column(Float, default=0)
    indirect_gmv = Column(Float, default=0)
    roi = Column(Float, default=0)
    cart_adds = Column(Integer, default=0)
    cart_rate = Column(Float, default=0)
    favs = Column(Integer, default=0)
    new_buyers = Column(Integer, default=0)
    members_gmv = Column(Float, default=0)

    imported_at = Column(DateTime, default=func.now())
    direct_orders = Column(Integer, default=0)
    indirect_orders = Column(Integer, default=0)
    click_conversion = Column(Float, default=0)
    presale_roi = Column(Float, default=0)
    total_cost = Column(Float, default=0)
    direct_cart_adds = Column(Integer, default=0)
    indirect_cart_adds = Column(Integer, default=0)
    store_favs = Column(Integer, default=0)
    store_fav_cost = Column(Float, default=0)
    total_fav_cart = Column(Integer, default=0)
    total_fav_cart_cost = Column(Float, default=0)
    item_fav_cart = Column(Integer, default=0)
    item_fav_cart_cost = Column(Float, default=0)
    total_favs = Column(Integer, default=0)
    item_fav_cost = Column(Float, default=0)
    item_fav_rate = Column(Float, default=0)
    cart_cost = Column(Float, default=0)


class PaidSourceData(Base):
    __tablename__ = "paid_source_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(String, nullable=False, index=True)
    entity_id = Column(String, nullable=False, index=True)
    entity_type = Column(String, nullable=True)
    entity_name = Column(String, nullable=True)

    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    cost = Column(Float, default=0)
    ctr = Column(Float, default=0)
    cpc = Column(Float, default=0)
    cpm = Column(Float, default=0)

    presale_gmv = Column(Float, default=0)
    presale_orders = Column(Integer, default=0)
    direct_presale_gmv = Column(Float, default=0)
    direct_presale_orders = Column(Integer, default=0)
    indirect_presale_gmv = Column(Float, default=0)
    indirect_presale_orders = Column(Integer, default=0)
    direct_gmv = Column(Float, default=0)
    indirect_gmv = Column(Float, default=0)
    total_gmv = Column(Float, default=0)
    total_orders = Column(Integer, default=0)
    direct_orders = Column(Integer, default=0)
    indirect_orders = Column(Integer, default=0)
    click_conversion = Column(Float, default=0)
    roi = Column(Float, default=0)
    roi_with_presale = Column(Float, default=0)
    order_cost = Column(Float, default=0)

    total_cart = Column(Integer, default=0)
    direct_cart = Column(Integer, default=0)
    indirect_cart = Column(Integer, default=0)
    cart_rate = Column(Float, default=0)
    fav_items = Column(Integer, default=0)
    fav_store = Column(Integer, default=0)
    store_fav_cost = Column(Float, default=0)
    total_fav_cart = Column(Integer, default=0)
    total_fav_cart_cost = Column(Float, default=0)
    item_fav_cart = Column(Integer, default=0)
    item_fav_cart_cost = Column(Float, default=0)
    total_favs = Column(Integer, default=0)
    item_fav_cost = Column(Float, default=0)
    item_fav_rate = Column(Float, default=0)
    cart_cost = Column(Float, default=0)

    order_qty = Column(Integer, default=0)
    order_amount = Column(Float, default=0)
    direct_fav_items = Column(Integer, default=0)
    indirect_fav_items = Column(Integer, default=0)
    coupon_count = Column(Integer, default=0)
    wallet_recharge_qty = Column(Integer, default=0)
    wallet_recharge_amount = Column(Float, default=0)
    wangwang_consult = Column(Integer, default=0)
    guide_visits = Column(Integer, default=0)
    guide_visitors = Column(Integer, default=0)
    guide_potential = Column(Integer, default=0)
    guide_potential_ratio = Column(Float, default=0)
    member_rate = Column(Float, default=0)
    member_count = Column(Integer, default=0)
    guide_visit_rate = Column(Float, default=0)
    deep_visits = Column(Integer, default=0)
    avg_pages = Column(Float, default=0)
    new_buyers = Column(Integer, default=0)
    new_buyer_ratio = Column(Float, default=0)
    member_first_buy = Column(Integer, default=0)
    member_gmv = Column(Float, default=0)
    member_orders = Column(Integer, default=0)
    buyers = Column(Integer, default=0)
    orders_per_buyer = Column(Float, default=0)
    amount_per_buyer = Column(Float, default=0)
    organic_conversion = Column(Float, default=0)
    organic_exposure = Column(Integer, default=0)
    platform_boost_gmv = Column(Float, default=0)
    platform_boost_direct = Column(Float, default=0)
    platform_boost_clicks = Column(Integer, default=0)
    coupon_discount = Column(Float, default=0)
    coupon_leverage_gmv = Column(Float, default=0)
    coupon_leverage_direct = Column(Float, default=0)
    coupon_leverage_clicks = Column(Integer, default=0)

    created_at = Column(DateTime, default=func.now())


class CampaignMetrics(Base):
    __tablename__ = "campaign_metrics"

    id = Column(Integer, primary_key=True, autoincrement=True)
    campaign_id = Column(String, nullable=False, unique=True, index=True)
    campaign_name = Column(String, nullable=True)
    campaign_type = Column(String, default="ztc")

    cost = Column(Float, default=0)
    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    conversions = Column(Integer, default=0)

    campaign_gmv = Column(Float, default=0)
    roi = Column(Float, default=0)
    cpa = Column(Float, default=0)
    cpm = Column(Float, default=0)
    ppc = Column(Float, default=0)

    status = Column(String, default="running")

    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())
