from sqlalchemy import Column, Integer, String, Float, DateTime
from sqlalchemy.sql import func
from app.core.database import Base


class MonthlyPlanning(Base):
    __tablename__ = "monthly_planning"

    id = Column(Integer, primary_key=True, autoincrement=True)
    plan_month = Column(String, nullable=False, index=True)
    product_id = Column(String, nullable=False, index=True)
    product_title = Column(String, nullable=True)
    category = Column(String, nullable=True)
    tier = Column(String, nullable=True)
    style = Column(String, nullable=True)
    scene = Column(String, nullable=True)
    manager = Column(String, nullable=True)
    new_old = Column(String, nullable=True)
    list_date = Column(String, nullable=True)
    image_url = Column(String, nullable=True)

    gsv_target = Column(Float, default=0)
    refund_target = Column(Float, default=0)
    net_sales_target = Column(Float, default=0)
    target_score = Column(Integer, default=0)
    daily_target = Column(Float, default=0)
    daily_target_ad = Column(Float, default=0)
    daily_target_ad_ratio = Column(Float, default=0)

    daily_visitors_target = Column(Integer, default=0)
    daily_conversion_target = Column(Float, default=0)
    daily_uv_value_target = Column(Float, default=0)

    payment_amount = Column(Float, default=0)
    refund_amount = Column(Float, default=0)
    net_sales = Column(Float, default=0)
    ad_spend = Column(Float, default=0)
    ad_roi = Column(Float, default=0)
    ad_ratio = Column(Float, default=0)
    visitors = Column(Integer, default=0)
    uv_value = Column(Float, default=0)
    payment_conversion = Column(Float, default=0)
    refund_rate = Column(Float, default=0)
    cart_rate = Column(Float, default=0)
    fav_rate = Column(Float, default=0)
    bounce_rate = Column(Float, default=0)
    avg_stay_duration = Column(Float, default=0)
    search_conversion = Column(Float, default=0)
    score = Column(Float, default=0)
    page_views = Column(Integer, default=0)
    payment_buyers = Column(Integer, default=0)
    aov = Column(Float, default=0)
    payment_qty = Column(Integer, default=0)
    cart_qty = Column(Integer, default=0)
    fav_users = Column(Integer, default=0)
    search_buyers = Column(Integer, default=0)
    search_ratio = Column(Float, default=0)
    search_uv_value = Column(Float, default=0)
    total_orders = Column(Integer, default=0)
    store_favs = Column(Integer, default=0)
    total_favs = Column(Integer, default=0)
    fav_cost = Column(Float, default=0)
    fav_cart_qty = Column(Integer, default=0)
    order_conversion = Column(Float, default=0)
    ctr = Column(Float, default=0)
    total_ad_spend = Column(Float, default=0)
    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    cart_items = Column(Integer, default=0)

    keyword_ad_spend = Column(Float, default=0)
    keyword_ad_sales = Column(Float, default=0)
    keyword_ad_roi = Column(Float, default=0)
    keyword_ad_conversion = Column(Float, default=0)
    keyword_impressions = Column(Integer, default=0)
    keyword_ctr = Column(Float, default=0)
    keyword_visitors = Column(Integer, default=0)
    keyword_visitor_ratio = Column(Float, default=0)
    keyword_ppc = Column(Float, default=0)
    keyword_conversion_cost = Column(Float, default=0)
    keyword_cart_qty = Column(Integer, default=0)
    keyword_cart_rate = Column(Float, default=0)
    keyword_cart_cost = Column(Float, default=0)

    audience_ad_spend = Column(Float, default=0)
    audience_ad_sales = Column(Float, default=0)
    audience_ad_roi = Column(Float, default=0)
    audience_ad_conversion = Column(Float, default=0)
    audience_impressions = Column(Integer, default=0)
    audience_ctr = Column(Float, default=0)
    audience_visitors = Column(Integer, default=0)
    audience_visitor_ratio = Column(Float, default=0)
    audience_ppc = Column(Float, default=0)
    audience_conversion_cost = Column(Float, default=0)
    audience_cart_qty = Column(Integer, default=0)
    audience_cart_rate = Column(Float, default=0)
    audience_cart_cost = Column(Float, default=0)

    full_site_ad_spend = Column(Float, default=0)
    full_site_ad_sales = Column(Float, default=0)
    full_site_ad_roi = Column(Float, default=0)
    full_site_ad_conversion = Column(Float, default=0)
    full_site_impressions = Column(Integer, default=0)
    full_site_ctr = Column(Float, default=0)
    full_site_visitors = Column(Integer, default=0)
    full_site_visitor_ratio = Column(Float, default=0)
    full_site_ppc = Column(Float, default=0)
    full_site_conversion_cost = Column(Float, default=0)
    full_site_cart_qty = Column(Integer, default=0)
    full_site_cart_rate = Column(Float, default=0)
    full_site_cart_cost = Column(Float, default=0)

    created_at = Column(DateTime, default=func.now())
