from sqlalchemy import Column, Integer, String, Float, DateTime, Index
from sqlalchemy.sql import func
from app.core.database import Base


class DailyData(Base):
    __tablename__ = "daily_data"
    __table_args__ = (
        Index('ix_daily_data_product_date', 'product_id', 'date'),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(String, nullable=False, index=True)
    date = Column(String, nullable=False, index=True)

    payment_amount = Column(Float, default=0)
    refund_amount = Column(Float, default=0)
    net_sales = Column(Float, default=0)
    payment_qty = Column(Integer, default=0)
    ipv = Column(Integer, default=0)
    pv = Column(Integer, default=0)
    search_ipv = Column(Integer, default=0)
    recommend_ipv = Column(Integer, default=0)
    paid_ipv = Column(Integer, default=0)
    organic_ipv = Column(Integer, default=0)
    payment_conversion = Column(Float, default=0)
    cart_rate = Column(Float, default=0)
    fav_rate = Column(Float, default=0)
    bounce_rate = Column(Float, default=0)
    avg_stay_duration = Column(Float, default=0)
    ad_spend = Column(Float, default=0)
    ad_roi = Column(Float, default=0)
    direct_roi = Column(Float, default=0)
    total_roi = Column(Float, default=0)
    buyers = Column(Integer, default=0)
    avg_order_value = Column(Float, default=0)
    data_source = Column(String, nullable=True)
    imported_at = Column(DateTime, default=func.now())
    uv_value = Column(Float, default=0)
    cart_qty = Column(Integer, default=0)
    fav_users = Column(Integer, default=0)
    search_conversion = Column(Float, default=0)
    search_visitors = Column(Integer, default=0)
    cart_users = Column(Integer, default=0)
    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    ctr = Column(Float, default=0)
    repurchase_rate = Column(Float, default=0)
    repurchase_users = Column(Integer, default=0)
    cross_sell_qty = Column(Integer, default=0)
    cross_sell_rate = Column(Float, default=0)
    presale_amount = Column(Float, default=0)
    presale_qty = Column(Integer, default=0)
    store_favs = Column(Integer, default=0)
    total_favs = Column(Integer, default=0)
    fav_cost = Column(Float, default=0)
    search_ratio = Column(Float, default=0)
    search_uv_value = Column(Float, default=0)


class WeeklyData(Base):
    __tablename__ = "weekly_data"
    __table_args__ = (
        Index('ix_weekly_data_product_week', 'product_id', 'week_start'),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(String, nullable=False, index=True)
    week_start = Column(String, nullable=False, index=True)

    payment_amount = Column(Float, default=0)
    refund_amount = Column(Float, default=0)
    net_sales = Column(Float, default=0)
    presale_amount = Column(Float, default=0)
    presale_qty = Column(Integer, default=0)
    ipv = Column(Integer, default=0)
    pv = Column(Integer, default=0)
    search_ipv = Column(Integer, default=0)
    recommend_ipv = Column(Integer, default=0)
    paid_ipv = Column(Integer, default=0)
    organic_ipv = Column(Integer, default=0)
    payment_conversion = Column(Float, default=0)
    cart_rate = Column(Float, default=0)
    fav_rate = Column(Float, default=0)
    search_click_rate = Column(Float, default=0)
    bounce_rate = Column(Float, default=0)
    avg_stay_duration = Column(Float, default=0)
    ad_spend = Column(Float, default=0)
    ad_roi = Column(Float, default=0)
    repurchase_rate = Column(Float, default=0)
    repurchase_users = Column(Integer, default=0)
    cross_sell_qty = Column(Integer, default=0)
    cross_sell_rate = Column(Float, default=0)
    avg_order_value = Column(Float, default=0)
    category_width = Column(Integer, default=0)
    action_1 = Column(String, nullable=True)
    action_2 = Column(String, nullable=True)
    data_source = Column(String, nullable=True)
    imported_at = Column(DateTime, default=func.now())
    industry_ctr = Column(Float, default=0)
    visitors = Column(Integer, default=0)
    search_visitors = Column(Integer, default=0)
    cart_count = Column(Integer, default=0)
    new_customers = Column(Integer, default=0)
    new_customer_cost = Column(Float, default=0)
    direct_cart_cost = Column(Float, default=0)
    total_cart_cost = Column(Float, default=0)
    search_ctr = Column(Float, default=0)
    total_roi = Column(Float, default=0)
    direct_roi = Column(Float, default=0)
    gsv_change = Column(Float, default=0)
    ad_spend_change = Column(Float, default=0)
    direct_roi_change = Column(Float, default=0)
    refund_ad_ratio = Column(Float, default=0)
    lead_potential_ratio = Column(Float, default=0)


class MonthlyData(Base):
    __tablename__ = "monthly_data"
    __table_args__ = (
        Index('ix_monthly_data_product_month', 'product_id', 'month'),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(String, nullable=False, index=True)
    month = Column(String, nullable=False, index=True)

    payment_amount = Column(Float, default=0)
    refund_amount = Column(Float, default=0)
    net_sales = Column(Float, default=0)
    visitors = Column(Integer, default=0)
    page_views = Column(Integer, default=0)
    uv_value = Column(Float, default=0)
    search_visitors = Column(Integer, default=0)
    search_ratio = Column(Float, default=0)
    payment_conversion = Column(Float, default=0)
    search_conversion = Column(Float, default=0)
    cart_rate = Column(Float, default=0)
    fav_rate = Column(Float, default=0)
    bounce_rate = Column(Float, default=0)
    avg_stay_duration = Column(Float, default=0)
    ad_spend = Column(Float, default=0)
    ad_roi = Column(Float, default=0)
    overall_roi = Column(Float, default=0)
    paid_ratio = Column(Float, default=0)
    refund_paid_ratio = Column(Float, default=0)
    keyword_spend = Column(Float, default=0)
    keyword_sales = Column(Float, default=0)
    keyword_roi = Column(Float, default=0)
    keyword_visitors = Column(Integer, default=0)
    keyword_ppc = Column(Float, default=0)
    crowd_spend = Column(Float, default=0)
    crowd_sales = Column(Float, default=0)
    crowd_roi = Column(Float, default=0)
    crowd_visitors = Column(Integer, default=0)
    crowd_ppc = Column(Float, default=0)
    site_spend = Column(Float, default=0)
    site_sales = Column(Float, default=0)
    site_roi = Column(Float, default=0)
    site_visitors = Column(Integer, default=0)
    site_ppc = Column(Float, default=0)
    refund_rate = Column(Float, default=0)
    repurchase_rate = Column(Float, default=0)
    cross_sell_rate = Column(Float, default=0)
    buyers = Column(Integer, default=0)
    avg_order_value = Column(Float, default=0)
    payment_qty = Column(Integer, default=0)
    cart_qty = Column(Integer, default=0)
    fav_users = Column(Integer, default=0)
    click_rate = Column(Float, default=0)
    score = Column(Integer, default=0)
    data_source = Column(String, nullable=True)
    imported_at = Column(DateTime, default=func.now())
    paid_ipv = Column(Integer, default=0)
    organic_ipv = Column(Integer, default=0)
    search_ipv = Column(Integer, default=0)
    recommend_ipv = Column(Integer, default=0)
    cart_users = Column(Integer, default=0)
    industry_ctr = Column(Float, default=0)
    cross_sell_qty = Column(Integer, default=0)
    cross_sell_categories = Column(Integer, default=0)
    repurchase_users = Column(Integer, default=0)
    guide_visits = Column(Integer, default=0)
    guide_visitors = Column(Integer, default=0)
    guide_potential = Column(Integer, default=0)
    guide_potential_ratio = Column(Float, default=0)
    new_buyers = Column(Integer, default=0)
    new_buyer_ratio = Column(Float, default=0)


class SalesSourceMonthly(Base):
    __tablename__ = "sales_source_monthly"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(String, nullable=False, index=True)
    category = Column(String, nullable=True)

    payment_amount = Column(Float, default=0)
    store_customers = Column(Integer, default=0)
    avg_stay_duration = Column(Float, default=0)
    payment_buyers = Column(Integer, default=0)
    payment_conversion = Column(Float, default=0)
    aov = Column(Float, default=0)
    repurchase_rate = Column(Float, default=0)
    repurchase_buyers = Column(Integer, default=0)
    repurchase_amount = Column(Float, default=0)
    payment_orders = Column(Integer, default=0)
    payment_qty = Column(Integer, default=0)
    visitors = Column(Integer, default=0)
    page_views = Column(Integer, default=0)
    refund_amount = Column(Float, default=0)
    refund_rate = Column(Float, default=0)
    net_payment = Column(Float, default=0)
    cart_qty = Column(Integer, default=0)
    cart_users = Column(Integer, default=0)
    fav_users = Column(Integer, default=0)
    consult_rate = Column(Float, default=0)
    wangwang_response_time = Column(Float, default=0)
    shipping_rate_24h = Column(Float, default=0)
    delivery_time_hours = Column(Float, default=0)
    refund_process_days = Column(Float, default=0)
    refund_success_rate = Column(Float, default=0)
    platform_dispute_rate = Column(Float, default=0)

    full_site_ad_spend = Column(Float, default=0)
    keyword_ad_spend = Column(Float, default=0)
    audience_ad_spend = Column(Float, default=0)
    scene_ad_spend = Column(Float, default=0)
    taoke_commission = Column(Float, default=0)
    total_cost = Column(Float, default=0)

    old_buyers = Column(Integer, default=0)
    revisit_buyers = Column(Integer, default=0)
    consult_users = Column(Integer, default=0)
    content_viewers = Column(Integer, default=0)
    past_buyers = Column(Integer, default=0)
    wangwang_satisfaction = Column(Float, default=0)
    total_payment = Column(Float, default=0)
    shipping_rate_48h = Column(Float, default=0)
    related_products = Column(Integer, default=0)
    content_scale = Column(Integer, default=0)
    dispute_rate = Column(Float, default=0)
    product_coverage = Column(Float, default=0)
    broadcast_hours = Column(Float, default=0)
    consult_conversion = Column(Float, default=0)
    old_buyer_amount = Column(Float, default=0)
    public_video_count = Column(Integer, default=0)
    total_orders = Column(Integer, default=0)
    stay_duration = Column(Float, default=0)

    created_at = Column(DateTime, default=func.now())


class ProductMonthlySummary(Base):
    __tablename__ = "product_monthly_summary"

    id = Column(Integer, primary_key=True, autoincrement=True)
    source_file = Column(String, nullable=True)
    month = Column(String, nullable=False, index=True)
    product_id = Column(String, nullable=False, index=True)
    product_title = Column(String, nullable=True)
    image_url = Column(String, nullable=True)
    category = Column(String, nullable=True)
    list_date = Column(String, nullable=True)

    payment_amount = Column(Float, default=0)
    refund_amount = Column(Float, default=0)
    net_sales = Column(Float, default=0)
    ad_spend = Column(Float, default=0)
    ad_roi = Column(Float, default=0)
    refund_paid_ratio = Column(Float, default=0)
    paid_ratio = Column(Float, default=0)
    visitors = Column(Integer, default=0)
    uv_value = Column(Float, default=0)
    payment_conversion = Column(Float, default=0)
    refund_rate = Column(Float, default=0)
    cart_rate = Column(Float, default=0)
    fav_rate = Column(Float, default=0)
    bounce_rate = Column(Float, default=0)
    avg_stay_duration = Column(Float, default=0)
    search_conversion = Column(Float, default=0)
    score = Column(Float, default=0)
    page_views = Column(Integer, default=0)
    payment_buyers = Column(Integer, default=0)
    aov = Column(Float, default=0)
    payment_qty = Column(Integer, default=0)
    cart_qty = Column(Integer, default=0)
    fav_users = Column(Integer, default=0)
    search_buyers = Column(Integer, default=0)
    search_ratio = Column(Float, default=0)
    search_uv_value = Column(Float, default=0)
    total_orders = Column(Integer, default=0)
    store_favs = Column(Integer, default=0)
    total_favs = Column(Integer, default=0)
    fav_cost = Column(Float, default=0)
    fav_cart_qty = Column(Integer, default=0)
    order_conversion = Column(Float, default=0)
    ctr = Column(Float, default=0)
    total_ad_spend = Column(Float, default=0)
    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    cart_items = Column(Integer, default=0)

    keyword_ad_spend = Column(Float, default=0)
    keyword_ad_sales = Column(Float, default=0)
    keyword_ad_roi = Column(Float, default=0)
    keyword_ad_conversion = Column(Float, default=0)
    keyword_impressions = Column(Integer, default=0)
    keyword_ctr = Column(Float, default=0)
    keyword_visitors = Column(Integer, default=0)
    keyword_visitor_ratio = Column(Float, default=0)
    keyword_ppc = Column(Float, default=0)
    keyword_conversion_cost = Column(Float, default=0)
    keyword_cart_qty = Column(Integer, default=0)
    keyword_cart_rate = Column(Float, default=0)
    keyword_cart_cost = Column(Float, default=0)

    audience_ad_spend = Column(Float, default=0)
    audience_ad_sales = Column(Float, default=0)
    audience_ad_roi = Column(Float, default=0)
    audience_ad_conversion = Column(Float, default=0)
    audience_impressions = Column(Integer, default=0)
    audience_ctr = Column(Float, default=0)
    audience_visitors = Column(Integer, default=0)
    audience_visitor_ratio = Column(Float, default=0)
    audience_ppc = Column(Float, default=0)
    audience_conversion_cost = Column(Float, default=0)
    audience_cart_qty = Column(Integer, default=0)
    audience_cart_rate = Column(Float, default=0)
    audience_cart_cost = Column(Float, default=0)

    full_site_ad_spend = Column(Float, default=0)
    full_site_ad_sales = Column(Float, default=0)
    full_site_ad_roi = Column(Float, default=0)
    full_site_ad_conversion = Column(Float, default=0)
    full_site_impressions = Column(Integer, default=0)
    full_site_ctr = Column(Float, default=0)
    full_site_visitors = Column(Integer, default=0)
    full_site_visitor_ratio = Column(Float, default=0)
    full_site_ppc = Column(Float, default=0)
    full_site_conversion_cost = Column(Float, default=0)
    full_site_cart_qty = Column(Integer, default=0)
    full_site_cart_rate = Column(Float, default=0)
    full_site_cart_cost = Column(Float, default=0)

    created_at = Column(DateTime, default=func.now())
