"""日度/周度/月度数据 ORM 模型"""
from models import db


class DailyData(db.Model):
    __tablename__ = 'daily_data'
    __table_args__ = (db.UniqueConstraint('product_id', 'date'),)

    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Text, db.ForeignKey('products.product_id'), nullable=False)
    date = db.Column(db.Date, nullable=False)
    payment_amount = db.Column(db.Float, default=0)
    refund_amount = db.Column(db.Float, default=0)
    net_sales = db.Column(db.Float, default=0)
    payment_qty = db.Column(db.Integer, default=0)
    ipv = db.Column(db.Integer, default=0)
    pv = db.Column(db.Integer, default=0)
    search_ipv = db.Column(db.Integer, default=0)
    recommend_ipv = db.Column(db.Integer, default=0)
    paid_ipv = db.Column(db.Integer, default=0)
    organic_ipv = db.Column(db.Integer, default=0)
    payment_conversion = db.Column(db.Float, default=0)
    cart_rate = db.Column(db.Float, default=0)
    fav_rate = db.Column(db.Float, default=0)
    bounce_rate = db.Column(db.Float, default=0)
    avg_stay_duration = db.Column(db.Float, default=0)
    ad_spend = db.Column(db.Float, default=0)
    ad_roi = db.Column(db.Float, default=0)
    buyers = db.Column(db.Integer, default=0)
    avg_order_value = db.Column(db.Float, default=0)
    uv_value = db.Column(db.Float, default=0)
    cart_qty = db.Column(db.Integer, default=0)
    fav_users = db.Column(db.Integer, default=0)
    search_conversion = db.Column(db.Float, default=0)
    search_visitors = db.Column(db.Integer, default=0)
    cart_users = db.Column(db.Integer, default=0)
    data_source = db.Column(db.Text)
    imported_at = db.Column(db.DateTime, default=db.func.current_timestamp())


class WeeklyData(db.Model):
    __tablename__ = 'weekly_data'
    __table_args__ = (db.UniqueConstraint('product_id', 'week_start'),)

    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Text, db.ForeignKey('products.product_id'), nullable=False)
    week_start = db.Column(db.Date, nullable=False)
    payment_amount = db.Column(db.Float, default=0)
    refund_amount = db.Column(db.Float, default=0)
    net_sales = db.Column(db.Float, default=0)
    presale_amount = db.Column(db.Float, default=0)
    presale_qty = db.Column(db.Integer, default=0)
    ipv = db.Column(db.Integer, default=0)
    pv = db.Column(db.Integer, default=0)
    search_ipv = db.Column(db.Integer, default=0)
    recommend_ipv = db.Column(db.Integer, default=0)
    paid_ipv = db.Column(db.Integer, default=0)
    organic_ipv = db.Column(db.Integer, default=0)
    payment_conversion = db.Column(db.Float, default=0)
    cart_rate = db.Column(db.Float, default=0)
    fav_rate = db.Column(db.Float, default=0)
    search_click_rate = db.Column(db.Float, default=0)
    bounce_rate = db.Column(db.Float, default=0)
    avg_stay_duration = db.Column(db.Float, default=0)
    ad_spend = db.Column(db.Float, default=0)
    ad_roi = db.Column(db.Float, default=0)
    repurchase_rate = db.Column(db.Float, default=0)
    repurchase_users = db.Column(db.Integer, default=0)
    cross_sell_qty = db.Column(db.Integer, default=0)
    cross_sell_rate = db.Column(db.Float, default=0)
    avg_order_value = db.Column(db.Float, default=0)
    category_width = db.Column(db.Integer, default=0)
    action_1 = db.Column(db.Text)
    action_2 = db.Column(db.Text)
    industry_ctr = db.Column(db.Float, default=0)
    data_source = db.Column(db.Text)
    imported_at = db.Column(db.DateTime, default=db.func.current_timestamp())


class MonthlyData(db.Model):
    __tablename__ = 'monthly_data'
    __table_args__ = (db.UniqueConstraint('product_id', 'month'),)

    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Text, db.ForeignKey('products.product_id'), nullable=False)
    month = db.Column(db.Text, nullable=False)
    payment_amount = db.Column(db.Float, default=0)
    refund_amount = db.Column(db.Float, default=0)
    net_sales = db.Column(db.Float, default=0)
    visitors = db.Column(db.Integer, default=0)
    page_views = db.Column(db.Integer, default=0)
    uv_value = db.Column(db.Float, default=0)
    search_visitors = db.Column(db.Integer, default=0)
    search_ratio = db.Column(db.Float, default=0)
    payment_conversion = db.Column(db.Float, default=0)
    search_conversion = db.Column(db.Float, default=0)
    cart_rate = db.Column(db.Float, default=0)
    fav_rate = db.Column(db.Float, default=0)
    bounce_rate = db.Column(db.Float, default=0)
    avg_stay_duration = db.Column(db.Float, default=0)
    ad_spend = db.Column(db.Float, default=0)
    ad_roi = db.Column(db.Float, default=0)
    overall_roi = db.Column(db.Float, default=0)
    paid_ratio = db.Column(db.Float, default=0)
    refund_paid_ratio = db.Column(db.Float, default=0)
    keyword_spend = db.Column(db.Float, default=0)
    keyword_sales = db.Column(db.Float, default=0)
    keyword_roi = db.Column(db.Float, default=0)
    keyword_visitors = db.Column(db.Integer, default=0)
    keyword_ppc = db.Column(db.Float, default=0)
    crowd_spend = db.Column(db.Float, default=0)
    crowd_sales = db.Column(db.Float, default=0)
    crowd_roi = db.Column(db.Float, default=0)
    crowd_visitors = db.Column(db.Integer, default=0)
    crowd_ppc = db.Column(db.Float, default=0)
    site_spend = db.Column(db.Float, default=0)
    site_sales = db.Column(db.Float, default=0)
    site_roi = db.Column(db.Float, default=0)
    site_visitors = db.Column(db.Integer, default=0)
    site_ppc = db.Column(db.Float, default=0)
    refund_rate = db.Column(db.Float, default=0)
    repurchase_rate = db.Column(db.Float, default=0)
    cross_sell_rate = db.Column(db.Float, default=0)
    buyers = db.Column(db.Integer, default=0)
    avg_order_value = db.Column(db.Float, default=0)
    payment_qty = db.Column(db.Integer, default=0)
    cart_qty = db.Column(db.Integer, default=0)
    fav_users = db.Column(db.Integer, default=0)
    click_rate = db.Column(db.Float, default=0)
    score = db.Column(db.Integer, default=0)
    # 迁移新增字段
    paid_ipv = db.Column(db.Integer, default=0)
    organic_ipv = db.Column(db.Integer, default=0)
    search_ipv = db.Column(db.Integer, default=0)
    recommend_ipv = db.Column(db.Integer, default=0)
    cart_users = db.Column(db.Integer, default=0)
    industry_ctr = db.Column(db.Float, default=0)
    cross_sell_qty = db.Column(db.Integer, default=0)
    cross_sell_categories = db.Column(db.Integer, default=0)
    repurchase_users = db.Column(db.Integer, default=0)
    guide_visits = db.Column(db.Integer, default=0)
    guide_visitors = db.Column(db.Integer, default=0)
    guide_potential = db.Column(db.Integer, default=0)
    guide_potential_ratio = db.Column(db.Float, default=0)
    new_buyers = db.Column(db.Integer, default=0)
    new_buyer_ratio = db.Column(db.Float, default=0)
    data_source = db.Column(db.Text)
    imported_at = db.Column(db.DateTime, default=db.func.current_timestamp())
