"""付费推广明细 ORM 模型"""
from models import db


class PaidDetail(db.Model):
    __tablename__ = 'paid_detail'
    __table_args__ = (db.UniqueConstraint('product_id', 'date_range'),)

    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Text, db.ForeignKey('products.product_id'), nullable=False)
    date_range = db.Column(db.Text, nullable=False)
    impressions = db.Column(db.Integer, default=0)
    clicks = db.Column(db.Integer, default=0)
    cost = db.Column(db.Float, default=0)
    ctr = db.Column(db.Float, default=0)
    cpc = db.Column(db.Float, default=0)
    cpm = db.Column(db.Float, default=0)
    total_gmv = db.Column(db.Float, default=0)
    total_orders = db.Column(db.Integer, default=0)
    direct_gmv = db.Column(db.Float, default=0)
    indirect_gmv = db.Column(db.Float, default=0)
    roi = db.Column(db.Float, default=0)
    cart_adds = db.Column(db.Integer, default=0)
    cart_rate = db.Column(db.Float, default=0)
    favs = db.Column(db.Integer, default=0)
    new_buyers = db.Column(db.Integer, default=0)
    members_gmv = db.Column(db.Float, default=0)
    # 迁移新增字段
    direct_orders = db.Column(db.Integer, default=0)
    indirect_orders = db.Column(db.Integer, default=0)
    click_conversion = db.Column(db.Float, default=0)
    presale_roi = db.Column(db.Float, default=0)
    total_cost = db.Column(db.Float, default=0)
    direct_cart_adds = db.Column(db.Integer, default=0)
    indirect_cart_adds = db.Column(db.Integer, default=0)
    store_favs = db.Column(db.Integer, default=0)
    store_fav_cost = db.Column(db.Float, default=0)
    total_fav_cart = db.Column(db.Integer, default=0)
    total_fav_cart_cost = db.Column(db.Float, default=0)
    item_fav_cart = db.Column(db.Integer, default=0)
    item_fav_cart_cost = db.Column(db.Float, default=0)
    total_favs = db.Column(db.Integer, default=0)
    item_fav_cost = db.Column(db.Float, default=0)
    item_fav_rate = db.Column(db.Float, default=0)
    cart_cost = db.Column(db.Float, default=0)
    imported_at = db.Column(db.DateTime, default=db.func.current_timestamp())
