from fastapi import APIRouter
from app.api import products, imports, dashboard, custom_fields, kpi, trends, ads, health, operations, lifecycle, refunds, targets, alerts, reviews, market, toolbox, compare, profit, inventory, pace, events, misc, data_export, promotion, recommendation, reports, realtime, prediction, collaboration, data_quality, backup, upload, settings, smart_import, system

api_router = APIRouter(prefix="/api")

api_router.include_router(products.router)
api_router.include_router(imports.router)
api_router.include_router(dashboard.router)
api_router.include_router(custom_fields.router)
api_router.include_router(kpi.router)
api_router.include_router(trends.router)
api_router.include_router(ads.router)
api_router.include_router(health.router)
api_router.include_router(operations.router)
api_router.include_router(lifecycle.router)
api_router.include_router(refunds.router)
api_router.include_router(targets.router)
api_router.include_router(alerts.router)
api_router.include_router(reviews.router)
api_router.include_router(market.router)
api_router.include_router(toolbox.router)
api_router.include_router(compare.router)
api_router.include_router(profit.router)
api_router.include_router(inventory.router)
api_router.include_router(pace.router)
api_router.include_router(events.router)
api_router.include_router(misc.router)
api_router.include_router(data_export.router)
api_router.include_router(promotion.router)
api_router.include_router(recommendation.router)
api_router.include_router(reports.router)
api_router.include_router(realtime.router)
api_router.include_router(prediction.router)
api_router.include_router(collaboration.router)
api_router.include_router(data_quality.router)
api_router.include_router(backup.router)
api_router.include_router(upload.router)
api_router.include_router(settings.router)
api_router.include_router(smart_import.router)
api_router.include_router(system.router)
